"""init

Revision ID: 0
Revises: 
Create Date: 2024-04-25 22:43:11.756882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_tag',
    sa.Column('value', sa.Enum('STABLE', 'POW', 'MEME', 'SOLANA', 'LAYER_1', 'LAYER_2', name='cointagtype'), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_pair',
    sa.Column('base_id', sa.Uuid(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['base_id'], ['coin.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['coin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coin_to_tag',
    sa.Column('coin_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['coin_tag.id'], ),
    sa.PrimaryKeyConstraint('coin_id', 'tag_id')
    )
    op.create_table('candlestick_data',
    sa.Column('open_time', sa.Integer(), nullable=False),
    sa.Column('close_time', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('quote_asset_volume', sa.Float(), nullable=False),
    sa.Column('number_of_trades', sa.Integer(), nullable=False),
    sa.Column('taker_buy_base_asset_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_asset_volume', sa.Float(), nullable=False),
    sa.Column('coin_pair_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['coin_pair_id'], ['coin_pair.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candlestick_data')
    op.drop_table('coin_to_tag')
    op.drop_table('coin_pair')
    op.drop_table('coin_tag')
    op.drop_table('coin')
    # ### end Alembic commands ###
